server:
  port: 5003

spring:
  application:
    name: booking-service

  datasource:
    url: "jdbc:mysql://localhost:3306/salon_bookingdb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mohitrhl001@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
