server:
  port: 5004

spring:
  application:
    name: category-service

  datasource:
    url: "jdbc:mysql://localhost:3306/salon_categorydb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mohitrhl001@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
