server:
  port: 5000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SALON-SERVICE
          uri: "lb://SALON-SERVICE"
          predicates:
            - Path= /salons/**, /api/salons/**, /api/admin/salons/**

        - id: USER-SERVICE
          uri: "lb://USER-SERVICE"
          predicates:
            - Path= /auth/**, /api/admin/users/**, /api/users/**, /users/**


        - id: SERVICE-OFFERING
          uri:
            "lb://SERVICE-OFFERING"
          predicates:
            - Path= /api/service-offering/**

        - id: CATEGORY-SERVICE
          uri:
            "lb://CATEGORY-SERVICE"
          predicates:
            - Path= /api/categories/**

        - id: BOOKING-SERVICE
          uri:
            "lb://BOOKING-SERVICE"
          predicates:
            - Path= /api/bookings/**

        - id: PAYMENT-SERVICE
          uri:
            "lb://PAYMENT-SERVICE"
          predicates:
            - Path= /api/payments/**

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
